### ISSUE TITLE
Add option to change default view mode of Listings page

### ISSUE THREAD

**Issue by surajv** [MyThemeShopTeam/wp-real-estate#13]

**Comment by christiaangieles** [comment]
Any workaround for the time being, to be able to set default view? I have a client where I'm using this, and it's rather crucial that it starts in the grid view.

**Comment by surajv** [comment]
Hello @christiaangieles,
This enhancement will be added in the v1.1.1 which is set to be released today.
Thanks.

**Comment by christiaangieles** [comment]
That sounds awesome, and neat for the ones needing it, and nice for me in the future. I ended up using a rather eloquently jquery workaround that worked out. 

jQuery( document ).ready(function( $ ) {
    $( "ul" ).addClass(function( index, currentClass ) {
      var addedClass;
     
      if ( currentClass === "wre-items" ) {
        addedClass = "grid-view cee-view";
      }
     
      return addedClass;
    });
    
});

**Comment by surajv** [comment]
Hello @christiaangieles,
We have pushed the v1.1.1 on wordpress.org
https://github.com/MyThemeShopTeam/wp-real-estate/releases/tag/v1.1.1
