### ISSUE TITLE
content is not loaded with theme Impreza 

### ISSUE THREAD

**Issue by Jimmi08** [MyThemeShopTeam/wp-real-estate#38]
Before buying pro version, I wanted to test this plugin with theme Impreza

The content of shortcodes is not loaded at all.  

After switching to the core theme, they work.  

https://themeforest.net/item/impreza-retina-responsive-wordpress-theme/6434280

**Comment by surajv** [comment]
Hi @Jimmi08, if a shortcode is working fine with the default WordPress theme, then that means there is a problem with the theme which is not printing it. Please contact the theme developer and let us know what they say.

Thank you.

**Comment by Jimmi08** [comment]
Hi, yes, I did it.  But the only link to this plugin is here (or from my dashboard page) and you have not updated readme on GitHub repo, still says comp only with 4.x , not 5.3 
Thanks for the quick answer

**Comment by surajv** [comment]
@Jimmi08 yes you are right, the latest version is present here https://wordpress.org/plugins/wp-real-estate/

**Comment by Jimmi08** [comment]
@surajv I am sorry, I couldn't find it there. Thanks

**Comment by surajv** [comment]
My pleasure!
